#!/bin/sh

### BEGIN INIT INFO
# Provides:        voltage-monitor
# Required-Start:  none
# Required-Stop:   none
# Default-Start:   2 3 4 5
# Default-Stop:    1
# Short-Description: Start the line voltage monitor
### END INIT INFO

. /lib/lsb/init-functions

DAEMON=/lwa/LineMonitoring/lineMonitor.py
PIDFILE=/var/run/lineMonitor.pid

#test -x $DAEMON || exit 5

DMM_OPTS="-c /lwa/LineMonitoring/defaults.cfg -l /lwa/LineMonitoring/logs/runtime.log"

LOCKFILE=/var/lock/lineMonitor

lock_can() {
	if [ -x /usr/bin/lockfile-create ]; then
		lockfile-create $LOCKFILE
		lockfile-touch $LOCKFILE &
		LOCKTOUCHPID="$!"
	fi
}

unlock_can() {
	if [ -x /usr/bin/lockfile-create ] ; then
		kill $LOCKTOUCHPID
		lockfile-remove $LOCKFILE
	fi
}

case $1 in
	start)
		log_daemon_msg "Starting lightning data server" "lineMonitor.py"
		lock_can
  		start-stop-daemon --start --quiet --oknodo --pidfile $PIDFILE --startas $DAEMON -- -p $PIDFILE $DMM_OPTS
		status=$?
		unlock_can
		log_end_msg $status
  		;;
	stop)
		log_daemon_msg "Stopping lightning data server" "lineMonitor.py"
  		start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
		log_end_msg $?
		rm -f $PIDFILE
  		;;
	restart|force-reload)
		$0 stop && sleep 2 && $0 start
  		;;
	try-restart)
		if $0 status >/dev/null; then
			$0 restart
		else
			exit 0
		fi
		;;
	reload)
		exit 3
		;;
	status)
		status_of_proc -p $PIDFILE $DAEMON "lightning data server"
		;;
	*)
		echo "Usage: $0 {start|stop|restart|try-restart|force-reload|status}"
		exit 2
		;;
esac
