name: Test
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.10', '3.12']
      fail-fast: false
    steps:
        - name: "Software Install - Ubuntu"
          run: |
            sudo apt-get update -q
            sudo apt-get install -y \
              build-essential \
              git \
              gzip \
              pkg-config
        - uses: actions/setup-python@v5.0.0
          with:
            python-version: ${{ matrix.python-version }}
        - uses: actions/checkout@v2
        - name: "Software Install - Python"
          run: |
            pip install \
              git-python \
              json_minify \
              numpy \
              pytz \
              requests \
              serial
        - name: Test
          run: |
            cd tests
            python -m unittest discover
